require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GeographicAreasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # GeographicArea. As you add validations to GeographicArea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GeographicAreasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all geographic_areas as @geographic_areas" do
      geographic_area = GeographicArea.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:geographic_areas)).to eq([geographic_area])
    end
  end

  describe "GET #show" do
    it "assigns the requested geographic_area as @geographic_area" do
      geographic_area = GeographicArea.create! valid_attributes
      get :show, params: {id: geographic_area.to_param}, session: valid_session
      expect(assigns(:geographic_area)).to eq(geographic_area)
    end
  end

  describe "GET #new" do
    before(:each) do
      sign_in_and_get_mappings
    end

    it "assigns a new geographic_area as @geographic_area" do
      get :new, params: {}, session: valid_session
      expect(assigns(:geographic_area)).to be_a_new(GeographicArea)
    end
  end

  describe "GET #edit" do
    it "assigns the requested geographic_area as @geographic_area" do
      geographic_area = GeographicArea.create! valid_attributes
      get :edit, params: {id: geographic_area.to_param}, session: valid_session
      expect(assigns(:geographic_area)).to eq(geographic_area)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new GeographicArea" do
        expect {
          post :create, params: {geographic_area: valid_attributes}, session: valid_session
        }.to change(GeographicArea, :count).by(1)
      end

      it "assigns a newly created geographic_area as @geographic_area" do
        post :create, params: {geographic_area: valid_attributes}, session: valid_session
        expect(assigns(:geographic_area)).to be_a(GeographicArea)
        expect(assigns(:geographic_area)).to be_persisted
      end

      it "redirects to the created geographic_area" do
        post :create, params: {geographic_area: valid_attributes}, session: valid_session
        expect(response).to redirect_to(GeographicArea.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved geographic_area as @geographic_area" do
        post :create, params: {geographic_area: invalid_attributes}, session: valid_session
        expect(assigns(:geographic_area)).to be_a_new(GeographicArea)
      end

      it "re-renders the 'new' template" do
        post :create, params: {geographic_area: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested geographic_area" do
        geographic_area = GeographicArea.create! valid_attributes
        put :update, params: {id: geographic_area.to_param, geographic_area: new_attributes}, session: valid_session
        geographic_area.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested geographic_area as @geographic_area" do
        geographic_area = GeographicArea.create! valid_attributes
        put :update, params: {id: geographic_area.to_param, geographic_area: valid_attributes}, session: valid_session
        expect(assigns(:geographic_area)).to eq(geographic_area)
      end

      it "redirects to the geographic_area" do
        geographic_area = GeographicArea.create! valid_attributes
        put :update, params: {id: geographic_area.to_param, geographic_area: valid_attributes}, session: valid_session
        expect(response).to redirect_to(geographic_area)
      end
    end

    context "with invalid params" do
      it "assigns the geographic_area as @geographic_area" do
        geographic_area = GeographicArea.create! valid_attributes
        put :update, params: {id: geographic_area.to_param, geographic_area: invalid_attributes}, session: valid_session
        expect(assigns(:geographic_area)).to eq(geographic_area)
      end

      it "re-renders the 'edit' template" do
        geographic_area = GeographicArea.create! valid_attributes
        put :update, params: {id: geographic_area.to_param, geographic_area: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested geographic_area" do
      geographic_area = GeographicArea.create! valid_attributes
      expect {
        delete :destroy, params: {id: geographic_area.to_param}, session: valid_session
      }.to change(GeographicArea, :count).by(-1)
    end

    it "redirects to the geographic_areas list" do
      geographic_area = GeographicArea.create! valid_attributes
      delete :destroy, params: {id: geographic_area.to_param}, session: valid_session
      expect(response).to redirect_to(geographic_areas_url)
    end
  end

end
